#!/usr/bin/env bash
trap cleanup EXIT

cleanup() {
  [[ -n $tmpdir ]] || return
  echo "----- Nuking $tmpdir -----"
  rm -fr "$tmpdir"
  tmpdir=""
}

shopt -s lastpipe
if ! command -v jq &>/dev/null; then
  echo "FATAL ERROR: jq not available, aborting."
  exit 1
fi

set -e

for f in "$@"; do
  if [[ $f =~ ([^/]+)/([^/]+)/([^/]+) ]]; then
    tap=${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
    ghrepo=${BASH_REMATCH[1]}/homebrew-${BASH_REMATCH[2]}
    fname=${BASH_REMATCH[3]}
    tmpdir=$(mktemp -d)
    cd "$tmpdir"
    echo "===== Bottling $f in $tmpdir ====="
    brew install --build-bottle "$f"
    root_url=$(brew info --json "$f" | jq -r '.[] | .bottle.stable.root_url')
    brew bottle --verbose --json --root-url="$root_url" "$f"
    brew bottle --merge --write --root-url="$root_url" --keep-old ./*.json
    echo "----- Uploading for $f -----"
    jq -r '.[].bottle.tags|.[]|"\(.local_filename) \(.filename)"' ./*.json | while read lf rf; do
      mv -v "$lf" "$rf" && gh release upload "${root_url##*/}" "$rf" -R "$ghrepo" --clobber
    done
    git -C $(brew --repo "$tap") push 
    echo "----- Reinstalling $f -----"
    brew rm "$f"
    brew install "$f"
    cd - &> /dev/null
    cleanup
  else
    echo "WARNING: $f not in <user>/<tap>/<formula> format, skipping."
  fi
done
