#!/usr/bin/env bash
trap cleanup EXIT

cleanup() {
  [[ -n $tmpdir ]] || return
  echo "----- Nuking $tmpdir -----"
  rm -fr "$tmpdir"
  tmpdir=""
}

fatal() {
  echo "FATAL ERROR: $*" >&2
  exit 1
}

jquery() {
  jq -r ".[] | $*" ./.base_json
}

shopt -s lastpipe
command -v jq &>/dev/null || fatal "jq not available"

set -e

for f in "$@"; do
  if [[ $f =~ ([^/]+)/([^/]+)/([^/]+) ]]; then
    tap=${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
    ghrepo=${BASH_REMATCH[1]}/homebrew-${BASH_REMATCH[2]}
    repodir=$(brew --repo "$ghrepo")
    fname=${BASH_REMATCH[3]}
    tmpdir=$(mktemp -d)
    cd "$tmpdir"
    echo "===== Bottling $f in $tmpdir ====="
    brew install --build-bottle "$f"
    brew info --json "$f" > ./.base_json
    fver=$(jquery .versions.stable)
    if [[ $(jquery '.bottle | length') == "0" && -s ${repodir}/.root_url_base ]]; then
      # New bottle section
      root_url=https://github.com/${ghrepo}/releases/download/${fname}-${fver}
      keep_old=()
    else
      root_url=$(jquery .bottle.stable.root_url)
      keep_old=(--keep-old)
    fi
    [[ $root_url != "null" ]] || fatal "unable to determine root URL"
    brew bottle --verbose --json --root-url="${root_url}" "$f"
    brew bottle --merge --write --root-url="${root_url}" "${keep_old[@]}" ./*.json
    echo "----- Uploading for $f -----"
    jq -r '.[].bottle.tags|.[]|"\(.local_filename) \(.filename)"' ./*.json | while read lf rf; do
      mv -v "$lf" "$rf"
      tag=${root_url##*/}
      if gh release view "$tag" -R "$ghrepo" >&/dev/null; then
        # Release already created
        gh release upload "$tag" "$rf" -R "$ghrepo" --clobber
      else
        # We need to create it with this new file
        gh release create "$tag" "$rf" -R "$ghrepo"
      fi
    done
    git -C $(brew --repo "$tap") push 
    echo "----- Reinstalling $f -----"
    brew rm "$f"
    brew install "$f"
    cd - &> /dev/null
    cleanup
  else
    echo "WARNING: $f not in <user>/<tap>/<formula> format, skipping."
  fi
done
