#!/usr/bin/env bash
currbranch=$(git branch --show-current)
if [[ $# -eq 0 ]]; then
  git branch -a
  exit 1
fi
for b in "$@"; do
  [[ $b == $currbranch ]] && git checkout master
  git push -d gromgit $b && git branch -D $b
done
git branch -a
